### ISSUE TITLE
Auto discover versions of ShellCheck

### ISSUE THREAD

**Issue by felipecrs** [vscode-shellcheck/shellcheck-binaries#4]
We can convert the release job into a matrix, dynamically generated, that contains all the versions from shellcheck.

**Comment by carlocorradini** [comment]
Nice feature.
The only thing is that Darwin arm64 is available only for:
```json
{ "tags":["0.7.1_1","0.7.2","0.7.2-1","0.8.0","0.9.0"] }
```
Therefore, previous versions will be without Darwin arm64

**Comment by felipecrs** [comment]
We can build all versions **starting from 0.7.1** in this case. And add some special conditions to take the correct revision for M1.

**Comment by carlocorradini** [comment]
`wtf` is tag `0.7.1_1` ahah why!!!
We will have to strip it down and re-add the - for Docker (only)

**Comment by felipecrs** [comment]
Just to mention, I initiated the work on https://github.com/vscode-shellcheck/shellcheck-binaries/pull/6, but I'm pausing it for now.

That's because the need isn't very strong. The ShellCheck release cadence is very low, and even if we add a job that fetches all versions of ShellCheck dynamically on every midnight, chances are that I'd be quicker to just add the new version here, as I follow the ShellCheck repository for new releases.

**Comment by carlocorradini** [comment]
No problem 🥳

**Comment by felipecrs** [comment]
NVM, it's not worth it at all.
